from fastapi import APIRouter

from .results.combined_panecho_echoprime_api import router as combined_panecho_echoprime_router
from .results.combined_dynamic_measurements_api import router as combined_dynamic_measurements_router
from .results.llm_report_get_api import router as llm_report_get_router
from .pipeline.pipeline_start_api import router as pipeline_start_router
from .pipeline.pipeline_status_api import router as pipeline_status_router
from .pipeline.pipeline_promote_api import router as pipeline_promote_router
from .pipeline.pipeline_cancel_api import router as pipeline_cancel_router
from .pipeline.pipeline_regenerate_api import router as pipeline_regenerate_router

router = APIRouter()

router.include_router(combined_panecho_echoprime_router)
router.include_router(combined_dynamic_measurements_router)
router.include_router(llm_report_get_router)
router.include_router(pipeline_start_router)
router.include_router(pipeline_status_router)
router.include_router(pipeline_promote_router)
router.include_router(pipeline_cancel_router)
router.include_router(pipeline_regenerate_router)
