services:
  horalix-viewer:
    container_name: horalix-viewer
    image: horalix-viewer:local-dev
    build:
      context: ../horalix_viewer/Viewers-3.12.0
      dockerfile: Dockerfile
      args:
        APP_CONFIG: config/default.js
        PUBLIC_URL: /
        PORT: 80
    ports:
      - "3001:80"
    volumes:
      - ./app-config.js:/usr/share/nginx/html/app-config.js:ro
      - ./orthanc-standalone.json:/usr/share/nginx/html/orthanc-standalone.json:ro
      - ./start-ohif.sh:/start-ohif.sh:ro
    command: ["/bin/sh", "/start-ohif.sh"]
    restart: unless-stopped
