// Data taken from https://github.com/CarDS-Yale/PanEcho/blob/main/content/tasks.md
// --- Descriptions ---
export const MEASUREMENT_DESCRIPTIONS = {
  "pericardial-effusion": "Pericardial effusion",
  EF: "Left ventricular (LV) ejection fraction",
  GLS: "Global longitudinal strain. Actual value is -1 times the model output",
  LVEDV: "LV end-diastolic volume",
  LVESV: "LV end-systolic volume",
  LVSV: "LV stroke volume",
  LVSize: "LV size",
  "LVWallThickness-increased-any": "Any level of LV hypertrophy (increased wall thickness)",
  "LVWallThickness-increased-modsev": "Moderate or greater LV hypertrophy (increased wall thickness)",
  LVSystolicFunction: "LV systolic function",
  LVWallMotionAbnormalities: "LV wall motion abnormalities",
  IVSd: "LV intraventricular septum thickness at diastole",
  LVPWd: "LV posterior wall thickness at diastole",
  LVIDs: "LV internal diameter at systole",
  LVIDd: "LV internal diameter at diastole",
  LVOTDiam: "LV outflow tract diameter",
  LVDiastolicFunction: "LV diastolic function",
  "E|EAvg": "E/e' ratio",
  RVSP: "Right ventricular (RV) systolic pressure",
  RVSize: "RV size",
  RVSystolicFunction: "RV systolic function",
  RVIDd: "RV internal diameter at diastole",
  TAPSE: "Tricuspid annular plane systolic excursion",
  RVSVel: "RV systolic excursion velocity (RV S')",
  LASize: "Left atrial (LA) size",
  LAIDs2D: "LA internal diameter at systole",
  LAVol: "LA volume",
  RASize: "Right atrial (RA) size",
  "RADimensionM-L(cm)": "RA major dimension",
  AVStructure: "Aortic valve structure (bicuspid detection)",
  AVStenosis: "Aortic valve stenosis",
  "AVPkVel(m|s)": "Aortic valve peak velocity",
  AVRegurg: "Aortic valve regurgitation",
  LVOT20mmHg: "Elevated LV outflow tract pressure",
  MVStenosis: "Mitral valve stenosis",
  MVRegurgitation: "Mitral valve regurgitation",
  TVRegurgitation: "Tricuspid valve regurgitation",
  TVPkGrad: "Tricuspid valve peak gradient",
  "RAP-8-or-higher": "Elevated RA pressure",
  AORoot: "Transverse aortic root diameter",
};

// --- Units ---
export const MEASUREMENT_UNITS = {
  "pericardial-effusion": "",
  EF: "%",
  GLS: "%",
  LVEDV: "cm³",
  LVESV: "cm³",
  LVSV: "cm³",
  LVSize: "",
  "LVWallThickness-increased-any": "",
  "LVWallThickness-increased-modsev": "",
  LVSystolicFunction: "",
  LVWallMotionAbnormalities: "",
  IVSd: "cm",
  LVPWd: "cm",
  LVIDs: "cm",
  LVIDd: "cm",
  LVOTDiam: "cm",
  LVDiastolicFunction: "",
  "E|EAvg": "ratio",
  RVSP: "mmHg",
  RVSize: "",
  RVSystolicFunction: "",
  RVIDd: "cm",
  TAPSE: "cm",
  RVSVel: "cm/s",
  LASize: "",
  LAIDs2D: "cm",
  LAVol: "cm³",
  RASize: "",
  "RADimensionM-L(cm)": "cm",
  AVStructure: "",
  AVStenosis: "",
  "AVPkVel(m|s)": "m/s",
  AVRegurg: "",
  LVOT20mmHg: "",
  MVStenosis: "",
  MVRegurgitation: "",
  TVRegurgitation: "",
  TVPkGrad: "mmHg",
  "RAP-8-or-higher": "",
  AORoot: "cm",
};

// --- Class names for classification tasks ---
export const CLASS_NAMES = {
  "pericardial-effusion": ["Mild or Moderate or Severe"],
  LVSize: ["Mildly Increased", "Moderately or Severely Increased", "Normal"],
  "LVWallThickness-increased-any": ["Increased"],
  "LVWallThickness-increased-modsev": ["Moderately or Severely Increased"],
  LVSystolicFunction: ["Mildly Decreased", "Moderately or Severely Decreased", "Normal or Hyperdynamic"],
  LVWallMotionAbnormalities: ["None", "Present"],
  LVDiastolicFunction: ["Mild or Indeterminate", "Moderate or Severe", "Normal"],
  RVSize: ["Mildly Increased", "Moderately or Severely Increased", "Normal"],
  RVSystolicFunction: ["Decreased"],
  LASize: ["Mildly Dilated", "Moderately or Severely Dilated", "Normal"],
  RASize: ["Dilated"],
  AVStructure: ["Bicuspid"],
  AVStenosis: ["Mild or Moderate", "None", "Severe"],
  AVRegurg: ["Mild", "Moderate or Severe", "None or Trace"],
  LVOT20mmHg: ["Present"],
  MVStenosis: ["Mild or Moderate or Severe"],
  MVRegurgitation: ["Mild", "Moderate or Severe", "None or Trace"],
  TVRegurgitation: ["Mild", "Moderate or Severe", "None or Trace"],
  "RAP-8-or-higher": ["Present"],
};
