from fastapi import APIRouter

from .infer_primary_analysis_api import router as infer_primary_analysis_router
from .infer_secondary_analysis_api import router as infer_secondary_analysis_router
from .infer_motion_segmentation_api import router as infer_motion_segmentation_router
from .infer_linear_measurements_api import router as infer_linear_measurements_router
from .infer_spectral_measurements_api import router as infer_spectral_measurements_router

router = APIRouter()

router.include_router(infer_primary_analysis_router)
router.include_router(infer_secondary_analysis_router)
router.include_router(infer_motion_segmentation_router)
router.include_router(infer_linear_measurements_router)
router.include_router(infer_spectral_measurements_router)
