#!/usr/bin/env python3
from __future__ import annotations

import os
import sys
from pathlib import Path


ENV_KEY_NAME = "HORALIX_RELEASE_LICENSE_PUBLIC_KEY_B64"
FALLBACK_ENV_FILE_KEY = "LICENSE_PUBLIC_KEY_B64"
REPORTING_MODEL_ENV_KEY = "HORALIX_RELEASE_REPORTING_MODEL_ID"
FALLBACK_REPORTING_MODEL_KEYS = ("REPORTING_MODEL_ID",)
DEFAULT_REPORTING_MODEL_ID = "local-reporting-model"
OUTPUT_FILE_NAME = "generated_release_config.py"
RUNTIME_ENV_FILE_NAME = "generated_runtime.env"
RUNTIME_ENV_OMIT_KEYS = {
    "LICENSE_ENFORCEMENT",
    "LICENSE_PUBLIC_KEY_B64",
    "REPORTING_MODEL_ID",
}
RUNTIME_ENV_KEY_MAP = {
    "PRIMARY_ANALYSIS_PRELOAD": "PRIMARY_ANALYSIS_PRELOAD",
    "PRIMARY_ANALYSIS_WARMUP": "PRIMARY_ANALYSIS_WARMUP",
    "PRIMARY_ANALYSIS_BATCH": "PRIMARY_ANALYSIS_BATCH",
    "PRIMARY_ANALYSIS_DEVICE": "PRIMARY_ANALYSIS_DEVICE",
    "SECONDARY_ANALYSIS_PRELOAD": "SECONDARY_ANALYSIS_PRELOAD",
    "SECONDARY_ANALYSIS_WARMUP": "SECONDARY_ANALYSIS_WARMUP",
    "SECONDARY_ANALYSIS_DEVICE": "SECONDARY_ANALYSIS_DEVICE",
    "MOTION_SEGMENTATION_PRELOAD": "MOTION_SEGMENTATION_PRELOAD",
    "MOTION_SEGMENTATION_WARMUP": "MOTION_SEGMENTATION_WARMUP",
    "MOTION_SEGMENTATION_BATCH": "MOTION_SEGMENTATION_BATCH",
    "MOTION_SEGMENTATION_DEVICE": "MOTION_SEGMENTATION_DEVICE",
    "STUDY_MEASUREMENTS_PRELOAD": "STUDY_MEASUREMENTS_PRELOAD",
    "STUDY_MEASUREMENTS_WARMUP": "STUDY_MEASUREMENTS_WARMUP",
    "STUDY_MEASUREMENTS_BATCH": "STUDY_MEASUREMENTS_BATCH",
    "STUDY_MEASUREMENTS_DEVICE": "STUDY_MEASUREMENTS_DEVICE",
    "REPORTING_RESERVED_DEVICE": "REPORTING_RESERVED_DEVICE",
}


def _normalize_env_value(raw_value: str) -> str:
    value = raw_value.strip()
    if value and value[0] in {'"', "'"} and value[-1:] == value[0]:
        value = value[1:-1]
    return value.strip()


def _read_env_entries(env_path: Path) -> list[tuple[str, str]]:
    if not env_path.exists():
        return []

    entries: list[tuple[str, str]] = []
    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        candidate_key, raw_value = line.split("=", 1)
        entries.append((candidate_key.strip(), raw_value.strip()))

    return entries


def _read_env_value(env_path: Path, key: str) -> str:
    for candidate_key, raw_value in _read_env_entries(env_path):
        if candidate_key == key:
            return _normalize_env_value(raw_value)

    return ""


def _resolve_public_key() -> str:
    env_value = os.environ.get(ENV_KEY_NAME, "").strip()
    if env_value:
        return env_value

    env_path = Path(__file__).resolve().parents[1] / ".env"
    return _read_env_value(env_path, FALLBACK_ENV_FILE_KEY)


def _resolve_reporting_model_id() -> str:
    env_value = os.environ.get(REPORTING_MODEL_ENV_KEY, "").strip()
    if env_value:
        return env_value

    env_path = Path(__file__).resolve().parents[1] / ".env"
    for key in FALLBACK_REPORTING_MODEL_KEYS:
        resolved_value = _read_env_value(env_path, key)
        if resolved_value:
            return resolved_value
    return DEFAULT_REPORTING_MODEL_ID


def _write_release_config(output_path: Path, public_key_b64: str, reporting_model_id: str) -> None:
    content = (
        "# Auto-generated by generate_release_config.py. Do not edit.\n"
        "PACKAGED_LICENSE_ENFORCEMENT = True\n"
        f"PACKAGED_LICENSE_PUBLIC_KEY_B64 = {public_key_b64!r}\n"
        f"PACKAGED_REPORTING_MODEL_ID = {reporting_model_id!r}\n"
    )
    output_path.write_text(content, encoding="utf-8")


def _write_runtime_env(output_path: Path, env_entries: list[tuple[str, str]]) -> None:
    lines = [
        "# Auto-generated by generate_release_config.py. Do not edit.\n",
        "# License enforcement and verification key are embedded in packaged server builds.\n",
    ]
    normalized_entries: dict[str, str] = {}
    for key, raw_value in env_entries:
        if key in RUNTIME_ENV_OMIT_KEYS:
            continue
        normalized_key = RUNTIME_ENV_KEY_MAP.get(key, key)
        normalized_entries[normalized_key] = raw_value
    for key, raw_value in normalized_entries.items():
        lines.append(f"{key}={raw_value}\n")
    output_path.write_text("".join(lines), encoding="utf-8")


def main() -> int:
    env_path = Path(__file__).resolve().parents[1] / ".env"
    public_key_b64 = _resolve_public_key()
    if not public_key_b64:
        print(
            "Missing release license verification key. "
            f"Set {ENV_KEY_NAME} or LICENSE_PUBLIC_KEY_B64 in backend/.env before build.",
            file=sys.stderr,
        )
        return 1
    reporting_model_id = _resolve_reporting_model_id()

    output_dir = Path(__file__).resolve().parent
    release_config_path = output_dir / OUTPUT_FILE_NAME
    runtime_env_path = output_dir / RUNTIME_ENV_FILE_NAME

    _write_release_config(release_config_path, public_key_b64, reporting_model_id)
    _write_runtime_env(runtime_env_path, _read_env_entries(env_path))
    print(f"Wrote embedded release config to {release_config_path}")
    print(f"Wrote packaged runtime env to {runtime_env_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
