import React, { useEffect, useState } from "react";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "../../components/ui/card";
import { listInstancesApi } from "../../api/StudiesApi";
import { listDerivedResultsApi } from "../../api/StudiesApi";
import { inferEchonetDynamicLVSegmentationApi } from  "../../api/InferenceApi"
import { Loader2, AlertCircle } from "lucide-react";

const API_URL_UPLOADS = process.env.REACT_APP_API_URL_UPLOADS

const LVSegmentation = ({ studyUID }) => {
  const [videos, setVideos] = useState([]); // stores list of segmented .mp4 file paths
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (!studyUID) return;

    const fetchSegmentations = async () => {
      // --- Step 1: set loading state ---
      setLoading(true);
      setError(null);

      try {
        // --- Step 2: fetch all instances for this study ---
        const instances = await listInstancesApi(studyUID);
        const derivedResults = await listDerivedResultsApi(studyUID);
        const results = [];

        // --- Step 3: iterate through all instances ---
        for (const instance of instances) {
          const sopInstanceUID = instance.sop_instance_uid;
          const instanceId = instance.id;

          // --- Step 4: check if segmentation already exists in DerivedResults ---
          const row = derivedResults.find(
            r =>
              r.instance_id === instanceId &&
              r.type === "EchonetDynamic_LV_Segmentation"
          );

          if (row && row.value_json) {
            // --- Step 5: segmentation already exists → use stored path ---
            const json = JSON.parse(row.value_json);
            results.push({ uid: sopInstanceUID, path: json.outputfile });
          } else {
            // --- Step 6: no segmentation exists → run inference ---

            // 6a: call inference API with sop_instance_uid
            const response = await inferEchonetDynamicLVSegmentationApi(sopInstanceUID);

            // 6b: save returned output_path
            results.push({ uid: sopInstanceUID, path: response.output_file });
          }
        }

        // --- Step 7: save all results in state ---
        setVideos(results);
        setLoading(false);
      } catch (err) {
        console.error("[LV_Segmentation] Error:", err);
        setError("Failed to fetch LV segmentation results");
        setLoading(false);
      }
    };

    fetchSegmentations();
  }, [studyUID]);

  return (
    <Card className="card-clinical">
      <CardHeader>
        <CardTitle>LV Segmentation</CardTitle>
        <CardDescription>Generated by Echonet Dynamic</CardDescription>
      </CardHeader>
      <CardContent>
        {/* --- Loading Spinner --- */}
        {loading && (
          <div className="flex items-center justify-center py-6 text-muted-foreground">
            <Loader2 className="w-5 h-5 mr-2 animate-spin" />
            Running LV segmentation on study instances...
          </div>
        )}

        {/* --- Error Message --- */}
        {error && (
          <div className="flex items-center justify-center gap-2 py-6 text-red-500">
            <AlertCircle className="w-5 h-5" />
            {error}
          </div>
        )}

        {/* --- Video Results --- */}
        {!loading && !error && videos.length > 0 && (
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
            {videos.map(v => (
              <div key={v.uid} className="space-y-2">
                <h4 className="text-sm font-semibold">Instance: {v.uid}</h4>
                <video controls className="w-full rounded shadow">
                  <source src={`${API_URL_UPLOADS}/${v.path}`} type="video/mp4" />
                  Your browser does not support MP4 playback.
                </video>
              </div>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  );
};

export default LVSegmentation;
