import React, { useEffect, useState } from "react";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "../../components/ui/card";
import { inferEchoPrimeApi } from "../../api/InferenceApi";
import { Loader2, AlertCircle } from "lucide-react";

const Report = ({ studyUID }) => {
    const [report, setReport] = useState(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);

    useEffect(() => {
        if (!studyUID) return;

        const fetchReport = async () => {
            setLoading(true);
            setError(null);
            try {
                const data = await inferEchoPrimeApi(studyUID);
                setReport(data.report || "No report generated.");
            } catch (err) {
                console.error("[Report] Failed to fetch EchoPrime report: ", err);
                setError("Failed to generate report");
            } finally {
                setLoading(false);
            }
        };

        fetchReport();
    }, []);

        return (
        <Card className="card-clinical">
            <CardHeader>
                <CardTitle>AI Report</CardTitle>
                <CardDescription>Generated by EchoPrime</CardDescription>
            </CardHeader>
            <CardContent>
                {loading && (
                    <div className="flex items-center justify-center py-6 text-muted-foreground">
                        <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                        Generating report...
                    </div>
                )}

                {error && (
                    <div className="flex items-center justify-center gap-2 py-6 text-red-500">
                        <AlertCircle className="w-5 h-5" />
                        {error}
                    </div>
                )}

                {!loading && !error && report && (
                    <pre className="text-sm leading-relaxed whitespace-pre-wrap text-foreground">
                        {report}
                    </pre>
                )}
            </CardContent>
        </Card>
    );
};

export default Report;
