import React, { useEffect, useState, useRef } from "react";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "../../components/ui/card";
import { inferEchoPrimeApi } from "../../api/InferenceApi";
import { listDerivedResultsApi } from "../../api/StudiesApi"
import { Loader2, AlertCircle } from "lucide-react";

const Report = ({ studyUID }) => {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const startedRef = useRef(false);

  useEffect(() => {
    if (!studyUID) return;

    let timer;

    const fetchReport = async () => {
      setLoading(true);
      setError(null);

      try {
        // 1. Check if report already exists in DerivedResult
        const results = await listDerivedResultsApi(studyUID);
        const row = results.find(r => r.type === "EchoPrime_Report");

        if (row && row.value_json) {
          const json = JSON.parse(row.value_json);
          setReport(json.report);
          setLoading(false);
          return;
        }

        // 2. Trigger inference once if not started yet
        if (!startedRef.current) {
          startedRef.current = true;
          try {
            await inferEchoPrimeApi(studyUID);
          } catch (err) {
            console.error("[Report] EchoPrime inference failed:", err);
          }
        }

        // 3. Poll until report row exists
        timer = setInterval(async () => {
          const updated = await listDerivedResultsApi(studyUID);
          const r = updated.find(r => r.type === "EchoPrime_Report");
          if (r && r.value_json) {
            clearInterval(timer);
            const json = JSON.parse(r.value_json);
            setReport(json.report);
            setLoading(false);
          }
        }, 3000);
      } catch (err) {
        console.error("[Report] Failed to fetch report: ", err);
        setError("Failed to fetch report");
        setLoading(false);
      }
    };

    fetchReport();

    return () => {
      if (timer) clearInterval(timer);
    };
  }, [studyUID]);

  // --- Helper: parse report into sections ---
  const parseReport = (text) => {
    if (!text) return [];
    return text.split("[SEP]").map(section => section.trim()).filter(Boolean);
  };

  const sections = parseReport(report);

  return (
    <Card className="card-clinical">
      <CardHeader>
        <CardTitle>AI Report</CardTitle>
        <CardDescription>Generated by EchoPrime</CardDescription>
      </CardHeader>
      <CardContent>
        {loading && (
          <div className="flex items-center justify-center py-6 text-muted-foreground">
            <Loader2 className="w-5 h-5 mr-2 animate-spin" />
            Generating report...
          </div>
        )}

        {error && (
          <div className="flex items-center justify-center gap-2 py-6 text-red-500">
            <AlertCircle className="w-5 h-5" />
            {error}
          </div>
        )}

        {!loading && !error && report && (
          <div className="space-y-4 text-sm text-foreground">
            {sections.map((section, idx) => {
              const [header, ...bodyParts] = section.split(":");
              const body = bodyParts.join(":").trim();
              return (
                <div key={idx} className="p-2 border-l-4 rounded border-primary bg-muted/10">
                  <h4 className="font-semibold">{header.trim()}</h4>
                  <p className="ml-2">{body}</p>
                </div>
              );
            })}
          </div>
        )}
      </CardContent>
    </Card>
  );
};

export default Report;
